export const AUDIO_INTROS = {
  '/dashboard': '/audio/intro-dashboard.mp3',
  '/coach': '/audio/intro-coach.mp3',
  '/strategy/decision': '/audio/intro-kompass.mp3',
  '/analyse': '/audio/intro-analyse.mp3',
  '/masterclass': '/audio/intro-masterclass.mp3',
  '/gehalt': '/audio/intro-gehalt.mp3',
  '/applications': '/audio/intro-bewerbungen.mp3',
  '/marktwert': '/audio/intro-marktwert.mp3',
  '/salary-log': '/audio/intro-salary-log.mp3',
  '/pre-coaching': '/audio/intro-dokumente.mp3',
  '/network': '/audio/intro-netzwerk.mp3',
  '/branding': '/audio/intro-branding.mp3',
  '/strategy/exit': '/audio/intro-exit.mp3',
  '/career': '/audio/intro-karrierepfad.mp3',
  '/profile': '/audio/intro-profil.mp3',
};

export const AUDIO_TTS_FALLBACKS = {
  '/dashboard': 'Willkommen im Dashboard. Hier siehst du deinen Fortschritt auf einen Blick.',
  '/coach': 'Dein KI-Coach steht bereit. Stell mir eine Frage zu Karriere, Gehalt oder Bewerbungen.',
  '/strategy/decision': 'Der Entscheidungs-Kompass hilft dir, Klarheit über deinen nächsten Schritt zu gewinnen.',
  '/analyse': 'Die Karriereanalyse zeigt dir deine Stärken und Entwicklungsfelder in 13 Kompetenzfeldern.',
  '/masterclass': 'In der Masterclass findest du Lektionen zu allen Karriere-Themen.',
  '/gehalt': 'Die Gehaltsdatenbank zeigt dir, was der Markt für deine Position zahlt.',
  '/applications': 'Im Bewerbungs-Tracker verwaltest du alle deine Opportunities.',
  '/marktwert': 'Dein Marktwert zeigt, wie sich dein Wert durch abgeschlossene Lektionen entwickelt.',
  '/salary-log': 'Im Gehalts-Tagebuch dokumentierst du jede Verhandlung und jeden Erfolg.',
  '/pre-coaching': 'Im Dokumenten-Safe sammelst du alle wichtigen Unterlagen für dein Karriere-Profil.',
  '/network': 'Dein Netzwerk ist dein Karriere-Kapital. Pflege deine wichtigsten Kontakte.',
  '/branding': 'Personal Branding macht dich sichtbar. Optimiere dein LinkedIn-Profil.',
  '/strategy/exit': 'Die Exit-Strategie hilft dir beim strukturierten Wechsel.',
  '/career': 'Dein Karrierepfad zeigt deinen individuellen Entwicklungsweg.',
  '/profile': 'In deinem Profil verwaltest du deine persönlichen Daten und Einstellungen.',
};
